apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: py-api-gateway
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: py-api-route
spec:
  parentRefs:
    - name: py-api-gateway
  hostnames:
    - "jpgcp.shop"
    - "gateway.jpgcp.cloud"
    
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /pyapi
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
      backendRefs:
        - name: clusterip-py-api-svc
          port: 8000
    - matches:
      - path:
          type: PathPrefix
          value: /webhook
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
      backendRefs:
        - name: clusterip-py-webhook-svc
          port: 8000
